// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Base64.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

contract BrandGenesis is ERC721URIStorage, Ownable {
    using Strings for uint256;

    uint256 private _nextTokenId;

    struct BrandIdentity {
        string iconName;
        string pathData; // SVG path data stored directly
        string shape;
        string colorFrom;
        string colorTo;
    }

    mapping(uint256 => BrandIdentity) public brandIdentities;

    constructor() ERC721("BrandGenesis", "BRAND") Ownable(msg.sender) {}

    function mint(
        address to,
        string memory iconName,
        string memory pathData,
        string memory shape,
        string memory colorFrom,
        string memory colorTo
    ) public {
        uint256 tokenId = _nextTokenId++;

        brandIdentities[tokenId] = BrandIdentity({
            iconName: iconName,
            pathData: pathData,
            shape: shape,
            colorFrom: colorFrom,
            colorTo: colorTo
        });

        _mint(to, tokenId);
    }

    function tokenURI(
        uint256 tokenId
    ) public view override returns (string memory) {
        _requireOwned(tokenId);

        BrandIdentity memory brand = brandIdentities[tokenId];

        string memory svg = generateSVG(brand);

        string memory json = Base64.encode(
            bytes(
                string(
                    abi.encodePacked(
                        '{"name": "Brand #',
                        tokenId.toString(),
                        '", "description": "On-Chain Brand Identity generated by BrandGenesis AI", ',
                        '"image": "data:image/svg+xml;base64,',
                        Base64.encode(bytes(svg)),
                        '", ',
                        '"attributes": [',
                        '{"trait_type": "Icon", "value": "',
                        brand.iconName,
                        '"},',
                        '{"trait_type": "Shape", "value": "',
                        brand.shape,
                        '"},',
                        '{"trait_type": "Color From", "value": "',
                        brand.colorFrom,
                        '"},',
                        '{"trait_type": "Color To", "value": "',
                        brand.colorTo,
                        '"}'
                        "]}"
                    )
                )
            )
        );

        return string(abi.encodePacked("data:application/json;base64,", json));
    }

    function generateSVG(
        BrandIdentity memory brand
    ) internal pure returns (string memory) {
        string memory shapeElement;

        if (keccak256(bytes(brand.shape)) == keccak256(bytes("circle"))) {
            shapeElement = '<circle cx="32" cy="32" r="32" fill="url(#gradient)" />';
        } else if (
            keccak256(bytes(brand.shape)) == keccak256(bytes("square"))
        ) {
            shapeElement = '<rect width="64" height="64" fill="url(#gradient)" />';
        } else {
            shapeElement = '<rect width="64" height="64" rx="12" ry="12" fill="url(#gradient)" />';
        }

        return
            string(
                abi.encodePacked(
                    '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">',
                    '<defs><linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="',
                    brand.colorFrom,
                    '" /><stop offset="100%" stop-color="',
                    brand.colorTo,
                    '" /></linearGradient></defs>',
                    shapeElement,
                    '<g transform="translate(16, 16)"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">',
                    brand.pathData,
                    "</svg></g></svg>"
                )
            );
    }
}
